### ISSUE TITLE
Docker Compose Setup

### ISSUE THREAD

**Issue by leeray75** [leeray75/ai-mermaid-chart-generator#13]
1. Create a `docker-compose.yml` file in the root directory:
   ```yaml
   version: '3.8'
   services:
     frontend:
       build: ./nextjs-app
       ports:
         - '3000:3000'
       depends_on:
         - backend
     backend:
       build: ./nodejs-api
       ports:
         - '5000:5000'
       environment:
         - MONGO_URI=mongodb://mongo:27017/ai-mermaid
         - OPENAI_API_KEY=your_openai_api_key
       depends_on:
         - mongo
     mongo:
       image: mongo:latest
       ports:
         - '27017:27017'
       volumes:
         - mongo-data:/data/db
   volumes:
     mongo-data:
   ```

2. Run the app with Docker Compose:
   ```bash
   docker-compose up --build
   ```
